package msn;

import java.awt.Color;
import java.awt.Font;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author L
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    //Construtor
    public JanelaPrincipal() {
        initComponents();
        //Adicionando o icone do MSN
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icone.png")));
        //Proibindo o user de redimencionar a tela
        this.setResizable(false);

        //iniciar no centro
        this.setLocationRelativeTo(null);

        //Carregando conversas
        WhatsApp.carregarConversas();

        
        inicializacao();
    }

    //Metodo para inicializar o programa
    public void inicializacao() {
        //Pedindo dados (primeiro login)
        if (WhatsApp.getNome().equals("")) {
             DadosUsuario();
        }
        //Escondendo a aba de conversa
        minimizarConversa();
        //Atualizando o status
        definirStatus(WhatsApp.getStatusAt());
        //Atualizando perfil
        AlterarPerfil();
        //Atualizando conversas
        AtualizarConversas();
        //Deixando visivel
        this.setVisible(true);
    }

    //Pedindo dados do user pela primeira vez
    protected void DadosUsuario() {
        //Mensagem de "boas vindas"
        
        Icon iconeMSN = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icone.png")));
        
        JOptionPane.showMessageDialog(foto, "Bem vindo ao MSN \n Digite seus dados a seguir para seu cadastro:", "Bem vindo ao MSN!", JOptionPane.YES_OPTION, iconeMSN);
       
        String nome = "", numero = "";

        //Pedindo o nome do user
        try {
            do {
                nome = JOptionPane.showInputDialog(null, "Insira seu nome", "CADASTRO", JOptionPane.QUESTION_MESSAGE);
              
                if (nome.length() < 3 || nome.length() > 12) {
                    JOptionPane.showMessageDialog(null, "Erro, digite um nome entre 3 e 12 caracteres", "ERRO", JOptionPane.ERROR_MESSAGE);
                }

            } while (nome.length() < 3 || nome.length() > 12);
            //Caso ele feche a janela encerre o programa
        } catch (java.lang.NullPointerException e) {
            System.exit(0);
        }
        
        boolean pass;
        //Pedindo o numero do user
        try {
            do {
                pass = true;
                numero = JOptionPane.showInputDialog(null, "Insira seu numero \n (Apenas numeros com DDD e 11 caracteres)", "CADASTRO", JOptionPane.QUESTION_MESSAGE);
                
                if (numero.length() != 11) {
                    JOptionPane.showMessageDialog(null, "Erro, digite um numero válido", "ERRO", JOptionPane.ERROR_MESSAGE);
                } else {
                    //Verifica se são caractes validos pela tabela ascii
                    for (int i = 0; i < numero.length(); i++) {
                        if (numero.charAt(i) < 48 || numero.charAt(i) > 57) {
                            JOptionPane.showMessageDialog(null, "Erro, digite um numero válido", "ERRO", JOptionPane.ERROR_MESSAGE);
                            pass = false;
                        }
                    }
                }
            } while (numero.length() != 11 || pass == false);
            //Caso ele feche a janela encerre o programa
        } catch (java.lang.NullPointerException e) {
            System.exit(0);
        }
        
        //Formata o numero recebido
        numero = "(" + numero.substring(0, 2) + ")" + numero.substring(2, 7) + "-" + numero.substring(7, 11);
        
        //Aplicando dados
        WhatsApp.setNome(nome);
        WhatsApp.setNumero(numero);
    }

    //Atualização do perfil do usuario na interface
    protected void AlterarPerfil() {
        nome_user.setText(WhatsApp.getNome());
        status_user.setText(WhatsApp.getRecado());
        num_user.setText(WhatsApp.getNumero());
        letra_user.setText(WhatsApp.getNome().toUpperCase().charAt(0) + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        menu = new javax.swing.JPanel();
        perfil = new javax.swing.JPanel();
        foto = new javax.swing.JPanel();
        letra_user = new javax.swing.JLabel();
        nome_user = new javax.swing.JLabel();
        status_user = new javax.swing.JLabel();
        num_user = new javax.swing.JLabel();
        minimizar = new javax.swing.JToggleButton();
        pesquisa = new javax.swing.JTextField();
        add_conversa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        conversas = new javax.swing.JList<>();
        add_conversa1 = new javax.swing.JButton();
        linha = new javax.swing.JPanel();
        remover_contatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        conversa = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nome_contato = new javax.swing.JLabel();
        ultimaVisu = new javax.swing.JLabel();
        fotoContato = new javax.swing.JPanel();
        letra_receptor = new javax.swing.JLabel();
        num_contato = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mensagens = new javax.swing.JTextPane();
        inserirDados = new javax.swing.JPanel();
        entrada = new javax.swing.JTextField();
        enviar = new javax.swing.JButton();
        trocar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        userSelecionado = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        alterar_nome = new javax.swing.JMenuItem();
        alterar_recado = new javax.swing.JMenuItem();
        alterar_status = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        conf = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        alterar_cor = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        jButton1.setText("jButton1");

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        setTitle("MSN ");
        setBackground(new java.awt.Color(36, 187, 223));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        menu.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                menuComponentHidden(evt);
            }
        });
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        perfil.setBackground(new java.awt.Color(0, 204, 204));
        perfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 51), 4, true));
        foto.setMaximumSize(new java.awt.Dimension(33, 40));
        foto.setMinimumSize(new java.awt.Dimension(33, 40));
        foto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letra_user.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        letra_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra_user.setText("A");
        foto.add(letra_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 30));

        perfil.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 12, 40, 50));

        nome_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nome_user.setText("Nome_User");
        perfil.add(nome_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 21));

        status_user.setText("#hashCode");
        perfil.add(status_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 44, -1, 20));

        num_user.setBackground(new java.awt.Color(204, 204, 204));
        num_user.setFont(new java.awt.Font("Tahoma", 2, 9)); // NOI18N
        num_user.setForeground(new java.awt.Color(153, 153, 153));
        num_user.setText("(11)4002-8922");
        perfil.add(num_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 70, -1));

        minimizar.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        minimizar.setText("<");
        minimizar.setToolTipText("Minimizar conversa");
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });
        perfil.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 40, -1));

        menu.add(perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 78));

        pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed(evt);
            }
        });
        pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pesquisaKeyPressed(evt);
            }
        });
        menu.add(pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 85, 100, -1));

        add_conversa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        add_conversa.setText("Pesquisar");
        add_conversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_conversaActionPerformed(evt);
            }
        });
        menu.add(add_conversa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 80, -1));

        conversas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        conversas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                conversasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(conversas);

        menu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, 380));

        add_conversa1.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        add_conversa1.setText("+");
        add_conversa1.setToolTipText("Adicionar conversa");
        add_conversa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_conversa1ActionPerformed(evt);
            }
        });
        menu.add(add_conversa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 50, 40));

        linha.setBackground(new java.awt.Color(0, 0, 0));
        linha.setPreferredSize(new java.awt.Dimension(2, 2));

        javax.swing.GroupLayout linhaLayout = new javax.swing.GroupLayout(linha);
        linha.setLayout(linhaLayout);
        linhaLayout.setHorizontalGroup(
            linhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        linhaLayout.setVerticalGroup(
            linhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        menu.add(linha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -10, 2, 530));

        remover_contatos.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        remover_contatos.setText("-");
        remover_contatos.setToolTipText("Remover conversa");
        remover_contatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_contatosActionPerformed(evt);
            }
        });
        menu.add(remover_contatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 50, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel1.setText("Grupo HashCode - 2017");
        menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msn/refresh.png"))); // NOI18N
        refresh.setToolTipText("Atualizar lista de contatos");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        menu.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 48, 40));

        conversa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        conversa.setPreferredSize(new java.awt.Dimension(399, 128));
        conversa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nome_contato.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nome_contato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nome_contato.setText("Nome_Contato");
        jPanel1.add(nome_contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 240, -1));

        ultimaVisu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ultimaVisu.setText("UltimaVisu");
        jPanel1.add(ultimaVisu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 240, -1));

        fotoContato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 51), 4, true));
        fotoContato.setMaximumSize(new java.awt.Dimension(33, 40));
        fotoContato.setMinimumSize(new java.awt.Dimension(33, 40));
        fotoContato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letra_receptor.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        letra_receptor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letra_receptor.setText("A");
        fotoContato.add(letra_receptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 30));

        jPanel1.add(fotoContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 53));

        num_contato.setForeground(new java.awt.Color(204, 204, 204));
        num_contato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num_contato.setText("Numero_contato");
        jPanel1.add(num_contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, -1));

        conversa.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 350, 80));

        mensagens.setEditable(false);
        mensagens.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jScrollPane3.setViewportView(mensagens);

        conversa.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 280, 330));

        entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaActionPerformed(evt);
            }
        });
        entrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entradaKeyPressed(evt);
            }
        });

        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });

        trocar.setText("trocar");
        trocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel3.setText("Como: ");

        userSelecionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userSelecionado.setText("UserSelecionado");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setText("Chamar atenção");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton3.setText("Limpar mensagens");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inserirDadosLayout = new javax.swing.GroupLayout(inserirDados);
        inserirDados.setLayout(inserirDadosLayout);
        inserirDadosLayout.setHorizontalGroup(
            inserirDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserirDadosLayout.createSequentialGroup()
                .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addGroup(inserirDadosLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(inserirDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(inserirDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inserirDadosLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(trocar))
                    .addGroup(inserirDadosLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(userSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inserirDadosLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inserirDadosLayout.setVerticalGroup(
            inserirDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserirDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inserirDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviar))
                .addGroup(inserirDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inserirDadosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(inserirDadosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addGroup(inserirDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inserirDadosLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(trocar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(inserirDadosLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(userSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        conversa.add(inserirDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 290, 90));

        jMenu2.setText("Perfil");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        alterar_nome.setText("Alterar Nome");
        alterar_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_nomeActionPerformed(evt);
            }
        });
        jMenu2.add(alterar_nome);

        alterar_recado.setText("Alterar Recado");
        alterar_recado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_recadoActionPerformed(evt);
            }
        });
        jMenu2.add(alterar_recado);

        alterar_status.setText("Alterar Status");
        alterar_status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterar_statusMouseClicked(evt);
            }
        });
        alterar_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_statusActionPerformed(evt);
            }
        });

        jMenuItem8.setText("Disponivel");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        alterar_status.add(jMenuItem8);

        jMenuItem9.setText("Ocupado");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        alterar_status.add(jMenuItem9);

        jMenuItem7.setText("Ausente");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        alterar_status.add(jMenuItem7);

        jMenuItem10.setText("Offline");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        alterar_status.add(jMenuItem10);

        jMenu2.add(alterar_status);

        jMenuBar1.add(jMenu2);

        conf.setText("Configurações");
        conf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confKeyPressed(evt);
            }
        });

        jMenu3.setText("Design");

        alterar_cor.setText("Alterar cor foto de perfil");

        jMenuItem1.setText("Azul");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        alterar_cor.add(jMenuItem1);

        jMenuItem2.setText("Vermelho");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        alterar_cor.add(jMenuItem2);

        jMenuItem3.setText("Amarelo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        alterar_cor.add(jMenuItem3);

        jMenuItem4.setText("Verde");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        alterar_cor.add(jMenuItem4);

        jMenuItem5.setText("Rosa");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        alterar_cor.add(jMenuItem5);

        jMenuItem6.setText("Branco");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        alterar_cor.add(jMenuItem6);

        jMenu3.add(alterar_cor);

        jMenu4.setText("Alterar fonte da conversa");

        jMenuItem14.setText("Default");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuItem11.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jMenuItem11.setText("Impact");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem15.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jMenuItem15.setText("Comic Sans");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuItem16.setFont(new java.awt.Font("Jokerman", 0, 12)); // NOI18N
        jMenuItem16.setText("Jokerman");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem16);

        jMenu3.add(jMenu4);

        conf.add(jMenu3);

        jMenuItem12.setText("Limpar todas as mensagens");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        conf.add(jMenuItem12);

        jMenuItem13.setText("Excluir todos os contatos");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        conf.add(jMenuItem13);

        jMenuItem17.setText("Apagar conta e sair");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        conf.add(jMenuItem17);

        jMenuItem18.setText("Sobre");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        conf.add(jMenuItem18);

        jMenuBar1.add(conf);

        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conversa, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(conversa, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Opção para altaerar o nome do usuario
    private void alterar_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_nomeActionPerformed
        String nome = JOptionPane.showInputDialog("Insira o seu nome: ");

        try {
            if (nome.length() > 2 && nome.length() < 13) {
                WhatsApp.setNome(nome);
                AlterarPerfil();
            } else {
                JOptionPane.showMessageDialog(null, "Erro, nome inválido", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            //Caso o usuario feche a janela
        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Erro, operação não foi concluida", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_alterar_nomeActionPerformed

    //Alteração da cor da foto 
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        foto.setBackground(Color.blue);
        letra_user.setForeground(Color.white);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
//Alteração da cor da foto 
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        foto.setBackground(Color.green);
        letra_user.setForeground(Color.black);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
//Alteração da cor da foto 
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        foto.setBackground(Color.red);
        letra_user.setForeground(Color.white);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
//Alteração da cor da foto 
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        foto.setBackground(Color.yellow);
        letra_user.setForeground(Color.black);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
//Alteração da cor da foto 
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        foto.setBackground(Color.pink);
        letra_user.setForeground(Color.black);
    }//GEN-LAST:event_jMenuItem5ActionPerformed
//Alteração da cor da foto 
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        foto.setBackground(Color.white);
        letra_user.setForeground(Color.black);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    //Alteração de recado do perfil
    private void alterar_recadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_recadoActionPerformed
        String status = JOptionPane.showInputDialog("Insira o recado: ");

        try {
            if (status.length() <= 20 && status.length() > 1 && !status.contains("html")) {
                WhatsApp.setRecado(status);
                AlterarPerfil();
            } else {
                JOptionPane.showMessageDialog(null, "Erro, insira um status entre 2 e 20 caracteres", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (java.lang.NullPointerException e) {
            return;
        }
    }//GEN-LAST:event_alterar_recadoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    //Alteração do status do user, cor da foto
    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        definirStatus("Ocupado");
    }//GEN-LAST:event_jMenuItem9ActionPerformed
//Alteração do status do user, cor da foto
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        definirStatus("Disponível");
    }//GEN-LAST:event_jMenuItem8ActionPerformed
//Alteração do status do user, cor da foto
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        definirStatus("Ausente");
    }//GEN-LAST:event_jMenuItem7ActionPerformed
//Alteração do status do user, cor da foto
    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        definirStatus("Offline");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    //Define e muda a cor do status
    public void definirStatus(String status) {
        Border bordaAt;
        switch (status) {
            case "Disponível":
                bordaAt = BorderFactory.createLineBorder(Color.green, 4);
                foto.setBorder(bordaAt);
                break;
            case "Ocupado":
                bordaAt = BorderFactory.createLineBorder(Color.red, 4);
                foto.setBorder(bordaAt);
                break;
            case "Ausente":
                bordaAt = BorderFactory.createLineBorder(Color.orange, 4);
                foto.setBorder(bordaAt);
                break;
            case "Offline":
                bordaAt = BorderFactory.createLineBorder(Color.gray, 4);
                foto.setBorder(bordaAt);
                break;
        }
        WhatsApp.setStatusAt(status);

    }

    private void alterar_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_statusActionPerformed

    }//GEN-LAST:event_alterar_statusActionPerformed

    private void alterar_statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterar_statusMouseClicked

    }//GEN-LAST:event_alterar_statusMouseClicked

    //Botao pesquisa
    private void add_conversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_conversaActionPerformed
        if (pesquisa.getText().replace(" ", "").length() > 0) {
            pesquisar();
        }
    }//GEN-LAST:event_add_conversaActionPerformed

    //Cadastro de novo contato
    private void add_conversa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_conversa1ActionPerformed
        CriarContato novo = new CriarContato();
        novo.setVisible(true);
        AtualizarConversas();
    }//GEN-LAST:event_add_conversa1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    //Botão sair
    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        WhatsApp.salvarConversas();
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    //Botão eleção conversa
    private void conversasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_conversasValueChanged

        try {
            selecionarConversa();
        } catch (java.lang.NullPointerException e) {
            minimizarConversa();
        }
        AtualizarConversas();

    }//GEN-LAST:event_conversasValueChanged

    //Minimizando e zerando a conversa
    protected void minimizarConversa() {
        conversa.setVisible(false);
        minimizar.setVisible(false);
        linha.setVisible(false);
        this.setSize(190, 570);
        conversaAtual = null;
    }

    //Maximizando a conversa
    protected void maximizarConversa() {
        this.setSize(520, 569);
        mensagens.setText("");
        conversa.setVisible(true);
        minimizar.setVisible(true);
        linha.setVisible(true);
        inserirDados.setVisible(true);
    }

    //Atualiza as conversas
    public void AtualizarConversas() {
        conversas.setModel(WhatsApp.listaContatos());
    }

    //Seleção da conversa
    public void selecionarConversa() {

        //Verifica se o controle para apagar contatos esta ativado
        if (remover == true && (conversas.getSelectedIndex()) != -1) {

            //Remover conversa
            int resposta = 0;
            try {
                resposta = JOptionPane.showConfirmDialog(null, "Apagar contato de " + conversas.getSelectedValue() + "?",
                        "Confirmação", JOptionPane.WARNING_MESSAGE);
                //Erro ocorre pois ao alterar o valor chama o metodo 2 vezes
            } catch (java.util.ConcurrentModificationException e) {
            }

            if (resposta == 0) {
                try {
                    WhatsApp.removerConversa(WhatsApp.getContato(conversas.getSelectedValue()));
                    //Erro ocorre pois ao alterar o valor chama o metodo 2 vezes
                } catch (java.util.ConcurrentModificationException e) {
                }
                AtualizarConversas();
                remover = false;
                minimizarConversa();
            } else {
                remover = false;
            }

            conversas.setForeground(Color.black);
            remover_contatos.setBorder(null);

        } else if (conversas.getSelectedIndex() != -1) {
            maximizarConversa();
            addConversa();
        }

        conversas.clearSelection();
    }

    //Dados da conversa atual
    private Conversa conversaAtual;

    //Abrir dados da conversa atual na aba de conversas
    protected void addConversa() {

        conversaAtual = WhatsApp.conversaAt(WhatsApp.getContato(conversas.getSelectedValue()));

        emissor = true;
        nome_contato.setText(conversaAtual.getNomeContato());
        ultimaVisu.setText(conversaAtual.getUltimaVisu());
        letra_receptor.setText(Character.toUpperCase(conversaAtual.getNomeContato().charAt(0)) + "");
        num_contato.setText(conversaAtual.getContatoReceptor());
        userSelecionado.setText(WhatsApp.getNome());

        //Abrindo a conversa armazenada
        atualizar_mensagens();
    }

    //Pegando as mensagens de dentro da conversa
    public void atualizar_mensagens() {
        ultimaVisu.setText(WhatsApp.getVisualisado(conversaAtual));
        mensagens.setText(WhatsApp.receberMensagem(conversaAtual.getContatoReceptor(), entrada.getText()));
    }

    //Enviando a mensagem
    public void enviarMensagem() {

        if (entrada.getText().isEmpty() == false) {
            WhatsApp.mandarMensagem(conversaAtual.getContatoReceptor(), entrada.getText(), emissor);
        } else {
            JOptionPane.showMessageDialog(null, "Erro, digite uma mensagem para enviar", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        entrada.setText("");
        atualizar_mensagens();
    }

    //Pesquisa e aplica os resultados a Jlist
    protected void pesquisar() {
        maximizarConversa();
        inserirDados.setVisible(false);
        nome_contato.setText("'" + pesquisa.getText() + "'");
        num_contato.setText("PESQUISA");
        ultimaVisu.setText("");
        letra_receptor.setText("P");

        String resultPesquisa = WhatsApp.pesquisa(pesquisa.getText());

        mensagens.setText(resultPesquisa.equals("") == true ? "Não houve resultados" : resultPesquisa);
        pesquisa.setText("");
    }

    //Controle para remover conversas
    private boolean remover = false;

    //Botão para remover conversas
    private void remover_contatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_contatosActionPerformed
        conversas.clearSelection();
        if (remover == false) {
            Border bordaAt = BorderFactory.createLineBorder(Color.red, 4);
            conversas.setForeground(Color.red);
            remover_contatos.setBorder(bordaAt);
            remover = true;
        } else {
            conversas.setForeground(Color.black);
            remover_contatos.setBorder(null);
            remover = false;
        }

    }//GEN-LAST:event_remover_contatosActionPerformed

    //Botão para minimizar a aba de conversa
    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        minimizarConversa();
    }//GEN-LAST:event_minimizarActionPerformed


    private void pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaActionPerformed

    }//GEN-LAST:event_pesquisaActionPerformed

    private void menuComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_menuComponentHidden

    }//GEN-LAST:event_menuComponentHidden

    //Ação para quando fechar
    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        WhatsApp.salvarConversas();
        System.exit(0);
    }//GEN-LAST:event_formComponentHidden

    //Controle do emissor
    private boolean emissor = true;

    //Trocando receptor/emissor
    private void trocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocarActionPerformed

        emissor = !emissor;
        if (emissor == true) {
            userSelecionado.setText(WhatsApp.getNome());
        } else {
            userSelecionado.setText(conversaAtual.getNomeContato());
        }

    }//GEN-LAST:event_trocarActionPerformed

    //Botão para enviar mensagem
    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        enviarMensagem();
    }//GEN-LAST:event_enviarActionPerformed

    //Mandar mensagem (press enter)
    private void entradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entradaKeyPressed
        if (evt.getKeyCode() == 10) {
            enviarMensagem();
        }
    }//GEN-LAST:event_entradaKeyPressed

    //Botão refresh conversas
    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        AtualizarConversas();
    }//GEN-LAST:event_refreshActionPerformed

    private void entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaActionPerformed

    //Botão pesquisar
    private void pesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaKeyPressed
        if (evt.getKeyCode() == 10 && pesquisa.getText().replace(" ", "").length() > 0) {
            pesquisar();
        }

    }//GEN-LAST:event_pesquisaKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void confKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_confKeyPressed

    //Limpar todos os contatos
    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        WhatsApp.removerContatos();
        minimizarConversa();
        AtualizarConversas();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    //Limpar todas as conversas
    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        WhatsApp.removerMensagens(true, "");
        minimizarConversa();
    }//GEN-LAST:event_jMenuItem12ActionPerformed
    //Alterar fonte
    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        mensagens.setFont(new Font("sansserif", Font.PLAIN, 10));
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        mensagens.setFont(new Font("Impact", Font.PLAIN, 10));
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        mensagens.setFont(new Font("Comicsans", Font.PLAIN, 10));
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        mensagens.setFont(new Font("Jokerman", Font.PLAIN, 10));
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    //Chamar a atenção
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Point atual = this.getLocation();

        WhatsApp.mandarMensagem(conversaAtual.getContatoReceptor(), "**CHAMOU SUA ATENÇÃO***", emissor);
        atualizar_mensagens();

        this.setLocation(this.getX() + 50, this.getY());

        try {
            Thread.sleep(100);
        } catch (InterruptedException e) {
        }

        this.setLocation(atual);
        this.setLocation(this.getX(), this.getY() + 25);

        try {
            Thread.sleep(100);
        } catch (InterruptedException e) {
        }

        this.setLocation(atual);
        this.setLocation(this.getX() - 50, this.getY() - 25);

        try {
            Thread.sleep(100);
        } catch (InterruptedException e) {
        }

        this.setLocation(atual);
        this.setLocation(this.getX(), this.getY() - 25);

        try {
            Thread.sleep(100);
        } catch (InterruptedException e) {
        }

        this.setLocation(atual);
        this.setLocation(this.getX() - 50, this.getY() - 25);

        try {
            Thread.sleep(100);
        } catch (InterruptedException e) {
        }

        this.setLocation(atual);

    }//GEN-LAST:event_jButton2ActionPerformed

    //Limpar mensagens
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int resposta = 2;
        resposta = JOptionPane.showConfirmDialog(null, "Limpar conversa de " + conversaAtual.getNomeContato() + "?",
                "Confirmação", JOptionPane.WARNING_MESSAGE);

        if (resposta == 0) {
            WhatsApp.removerMensagens(false, conversaAtual.getContatoReceptor());
        } else {
            JOptionPane.showMessageDialog(null, "Erro, operação não foi concluida", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        atualizar_mensagens();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        int resposta = 2;
        resposta = JOptionPane.showConfirmDialog(null, "Deseja apagar sua conta?",
                "Confirmação", JOptionPane.WARNING_MESSAGE);

        if (resposta == 0) {
            this.setVisible(false);
            WhatsApp.apagarUser();
        } else {
            JOptionPane.showMessageDialog(null, "Erro, operação não foi concluida", "Erro", JOptionPane.ERROR_MESSAGE);
        }

        WhatsApp.salvarConversas();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
       JOptionPane.showMessageDialog(null, "  *PROJETO ENZO* \n Alan Mota (20951850)"
               + "\n Ana Carolina (20977369) \n Falmer Rodrigo (20955356) "
               + "\n Gabriela Damazo (20941503) \n Ingred Gomes (20918177)"
               + "\n Paulo Passos (20954050)", "Sobre o projeto", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_conversa;
    private javax.swing.JButton add_conversa1;
    private javax.swing.JMenu alterar_cor;
    private javax.swing.JMenuItem alterar_nome;
    private javax.swing.JMenuItem alterar_recado;
    private javax.swing.JMenu alterar_status;
    private javax.swing.JMenu conf;
    private javax.swing.JPanel conversa;
    private javax.swing.JList<String> conversas;
    private javax.swing.JTextField entrada;
    private javax.swing.JButton enviar;
    private javax.swing.JPanel foto;
    private javax.swing.JPanel fotoContato;
    private javax.swing.JPanel inserirDados;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel letra_receptor;
    private javax.swing.JLabel letra_user;
    private javax.swing.JPanel linha;
    private javax.swing.JTextPane mensagens;
    private javax.swing.JPanel menu;
    private javax.swing.JToggleButton minimizar;
    private javax.swing.JLabel nome_contato;
    private javax.swing.JLabel nome_user;
    private javax.swing.JLabel num_contato;
    private javax.swing.JLabel num_user;
    private javax.swing.JPanel perfil;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JButton refresh;
    private javax.swing.JButton remover_contatos;
    private javax.swing.JLabel status_user;
    private javax.swing.JButton trocar;
    private javax.swing.JLabel ultimaVisu;
    private javax.swing.JLabel userSelecionado;
    // End of variables declaration//GEN-END:variables

}
